RC4plus.exe : RC4plus_Function.o RC4plus.o
		 gcc RC4plus_Function.o RC4plus.o -o RC4plus.exe
RC4plus_Function.o : RC4plus.h RC4plus_Function.c
		        gcc -c RC4plus_Function.c
RC4plus.o : RC4plus.c
	    gcc -c RC4plus.c 
